# --- to identify this as a YAML file
---

- hosts: all
# 2 spaces next
  become: true
  tasks:

  - name: Install the Apache and the libapache2-mod-php package
    package:
    # 2 more spaces before the elements.
    # Created a list of plays 
      name: 
        # NOW I HAVE ADDED LOCALLY SIGNIFICATN VARIABLES 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      update_cache: yes
      state: latest
  


