# --- to identify this as a YAML file
---

- hosts: all
# 2 spaces next
  become: true
  tasks:


  - name: update respository index
    apt:
      update_cache: yes

  - name: Install the Apache2 package
  # 2 more spaces before the APT module
    apt:
    # 2 more spaces before the elements.
      name: apache2
      state: latest

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest