# --- to identify this as a YAML file
---

- hosts: all
# 2 spaces next
  become: true
  tasks:


  - name: update respository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install the Apache2 and the libapache2-mod-php package
  # 2 more spaces before the APT module
    apt:
    # 2 more spaces before the elements.
    # Created a list of plays 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


