# --- to identify this as a YAML file
---

- hosts: all
# 2 spaces next
  become: true
  pre_tasks:
  

  - name: Install updates (CentOS)
    tags: always
    dnf:
    
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  
  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


# This next section will target WEB_SERVERS only
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu web_servers
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS web_servers
    tags: apache, apache2, centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  # - name: Install the Apache and the libapache2-mod-php package
  #   package:
  #   # 2 more spaces before the elements.
  #   # Created a list of plays 
  #     name: 
  #       # NOW I HAVE ADDED LOCALLY SIGNIFICATN VARIABLES 
  #       - "{{ apache_package }}"
  #       - "{{ php_package }}"
  #     update_cache: yes
  #     state: latest


- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB (Ubuntu)

    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install MariaDB (CENTOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: Install file server
    tags: samba
#the package command is used instead of APT / DNF as they are both the same package name "samba"
    package:
      name: samba
      state: latest

  


  


