- name: install unzip
  package: 
    name: unzip
    state: latest

- name: install terraform.
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes #Tells it that the src is a remote network.
    mode: 0755
    owner: root
    group: root